version: 1.0.{build}
branches:
  only:
  - develop
  - master
image: Visual Studio 2022
configuration: Release
platform: x64
install:
- pwsh: dotnet tool restore
build_script:
- pwsh: dotnet cake
artifacts:
- path: out/bin
  name: MSIX-Hero
